#!/bin/bash
connection_number=`PGOPTIONS='--statement_timeout=0' psql -AqXt -c "SELECT count(*) FROM pg_stat_activity"`

case $connection_number in
	[1-50]*)
		echo "Ok - $connection_number are used"
		exit 0
		;;
	[50-100]*)
		echo "Warning - $connection_number are used"
		exit 1
		;;
esac
