#!/bin/bash
echo -n "max num threads: "
cat /proc/sys/kernel/threads-max
echo -n "max num of open sockets: "
sudo sysctl -a | grep somaxconn | head -1
echo -n "max number of file descriptors: "
cat /proc/sys/fs/file-max
